name: 測試並部屬

on:
    push:
        branches: [main]
    
    pull_request:
        branches: [main]

    workflow_dispatch:

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - name: 下載 repo
              uses: actions/checkout@v6

            - name: 檢查檔案
              run: |
                echo "檢查當前路徑: $(pwd)"
                echo "列出當前路徑的檔案:"
                ls -al
            
            - name: 設定Node.js 版本
              uses: actions/setup-node@v6
              with:
                node-version: 24
            - name: 安裝 npm 套件
              run: npm install

            - name: Typescript 型別檢查
              run: npm run typecheck
            
            - name: Eslint檢查
              run: npm run lint

